version: '3.8'

services:
  web:
    restart: always
    env_file: .env
    container_name: drf_sunny_days
    build: .
    command: bash -c "while !</dev/tcp/db/${DB_INTERNAL_PORT:-5432}; do sleep 1; done; python sunny_days/manage.py runserver 0.0.0.0:${WEB_INTERNAL_PORT:-8000}"
    volumes:
      - .:/app
    ports:
      - "${WEB_EXTERNAL_PORT:-8000}:${WEB_INTERNAL_PORT:-8000}"
    depends_on:
      - db
      - redis

  redis:
    container_name: drf_sunny_days_redis
    image: redis:latest
    ports:
      - "${REDIS_EXTERNAL_PORT:-6379}:${REDIS_INTERNAL_PORT:-6379}"
    restart: unless-stopped
    tty: true

  db:
    container_name: drf_sunny_days_db
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "8104:5432"
    expose:
      - 5432
    environment:
      - POSTGRES_USER=karl
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=drf_sunny_days
    restart: unless-stopped
    tty: true

volumes:
  postgres_data: